export enum SCREENS {
  DASHBOARD = 'DASHBOARD',
  GAME = 'GAME',
  MARKETPLACE = 'MARKETPLACE',
  LEVELS = 'LEVELS',
  LEVEL_ENTRANCE = 'LEVEL_ENTRANCE',
  GAME_FINISH = 'GAME_FINISH',
  THEMES = 'THEMES',
  DEV_MODE = 'DEV_MODE',
}
