export enum SCREENS {
  DASHBOARD = 'DASHBOARD',
  PROFILE = 'PROFILE',
  LEADERBOARD = 'LEADERBOARD',
  ACHIEVEMENTS = 'ACHIEVEMENTS',
  GAME = 'GAME',
  MARKETPLACE = 'MARKETPLACE',
  LEVELS = 'LEVELS',
  GAME_FINISH = 'GAME_FINISH',
}
