export enum SCREENS {
  DASHBOARD = 'DASHBOARD',
  PROFILE = 'PROFILE',
  LEADERBOARD = 'LEADERBOARD',
  ACHIEVEMENTS = 'ACHIEVEMENTS',
  GAME = 'GAME',
  MARKETPLACE = 'MARKETPLACE',
  LEVELS = 'LEVELS',
  LEVEL_ENTRANCE = 'LEVEL_ENTRANCE',
  GAME_FINISH = 'GAME_FINISH',
  THEMES = 'THEMES',
}
